pull_request_rules:
  - name: automerge to master with label automerge
    conditions:
      - base=master
      - label!=WIP
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: merge