pull_request_rules:
  - name: automerge to master with label automerge
    conditions:
      - base=master
      - label!=WIP
      - "check-success=Travis CI - Pull Request"
    actions:
      merge:
        method: merge
