language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-5
    - gcc-5
    - cmake
    - libboost1.55-all-dev
    - valgrind

compiler:
- gcc

notifications:
  email:
    recipients:
      - alekstheod@gmail.com
    on_success: always
    on_failure: always

before_script:
- cd src
 
script: 
- export CXX="g++-5" CC="gcc-5"
- g++-5 --version
- echo $CXX $CC
- cmake -DCMAKE_DISABLE_FIND_PACKAGE_OpenCL:bool=TRUE CMakeLists.txt
- make
- valgrind --leak-check=full --error-exitcode=1 ./Test/Test 1000
after_success:
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi
- git checkout master
- git pull
- git checkout development
- git merge master
- git checkout master
- git merge development
- git push origin master
branches:
  only:
  - master
  - development
  email: alekstheod@gmail.com
os:
- linux

