language: cpp
addons:
  apt:
    packages:
      - gcc
      - g++
      - wget
      - git
      - clang
      - pocl2

install:
  - sudo wget -O /usr/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64
  - sudo chmod +x /usr/bin/bazelisk

notifications:
  email:
    recipients:
      - alekstheod@gmail.com
    on_success: always
    on_failure: always

script:
  - cd src && bazelisk build --config=asan //...
  - cd src && bazelisk test --config=asan //... --test_tag_filters="-openCL"
before_script:

os:
  - linux
dist: jammy
