language: cpp
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-5
    - gcc-5
    - libboost1.54-all-dev
    - cmake
    - valgrind
compiler:
- gcc
notifications:
  email:
    recipients:
    - alekstheod@gmail.com
    on_success: always
    on_failure: always
before_script:
- cd src
script:
- apt-cache search boost
- export CXX="g++-5" CC="gcc-5"
- g++-5 --version
- echo $CXX $CC
- cmake -DCMAKE_DISABLE_FIND_PACKAGE_OpenCL:bool=TRUE CMakeLists.txt
- make
- valgrind --leak-check=full --error-exitcode=1 ./Test/Test 1000 > /dev/null
- valgrind --leak-check=full --error-exitcode=1 ./NeuralNetwork/NeuralNetwork_ut/NeuralNetwork_ut
after_success:
- cd ..
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi
- git checkout -b master
- git pull
- git checkout -b development
- git merge master
- git checkout -b master
- git merge development
- git push -f -q https://alekstheod:$GITHUB_API_KEY@github.com/alekstheod/tnnlib master>/dev/null
branches:
  only:
  - development
  - master
  email: alekstheod@gmail.com
os:
- linux
dist: trusty
