language: cpp
compiler:
- gcc
- clang
apt:
sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
packages:
    - clang-3.7
    - g++-5
    - gcc-5
    - cmake-3.3.2
    - valgrind-3.11.0

before_script:
- cd src
script: 
- CXX="g++-5" && CC="gcc-5" && cmake CMakeLists.txt
- make
after_success:
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi
branches:
  only:
  - master
  email: alekstheod@gmail.com
env:
  global:
  - secure: olbok/GN6rOYvPnHBYWGz7giCoCdLFpT/7WSBHukYO3E0uNeqAUOOgW2BFOwCVWdSEJ/iTvJXZQ4qVZHX+6jRfvILZeGv+D2P93VdD8UFQRoTOfFC7esAo525s9fuKm9ehUGWZxlzGOBHHckky1jn6pEf8mlXAVM5e76dlH0fck=
  - secure: aqG9eB/PrzQ7XJQN6YX/00sNVvwSB77saxXQzguL2WFjAXB74h6168Hzq+awHtNX/vfOb6ta7fpWLHrA0D+gmZnvTR29VlP6nd0vs1tkdX1/jWbiBHjamRffp+NWVdKbJKYn5iLOGXcuUMOzY/opLKOdvxKZfkxGMxR2tTNLZUE=
os:
- linux
- osx