language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-5
    - gcc-5
    - cmake
    - libboost1.55-all-dev

compiler:
- gcc

notifications:
  slack:
    on_success: always

before_script:
- cd src

script: 
- export CXX="g++-5" CC="gcc-5"
- g++-5 --version
- echo $CXX $CC
- cmake -DCMAKE_DISABLE_FIND_PACKAGE_OpenCL:bool=TRUE CMakeLists.txt
- make
after_success:
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi
branches:
  only:
  - master
  email: alekstheod@gmail.com
os:
- linux

