language: cpp
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    - lvm-toolchain-xenial-5.0
    - sourceline: 'ppa:mamarley/updates'
    packages:
    - clang
    - valgrind
    - g++-7
    - clang-5.0
  env:
    - CXX=clang++-5.0
    - CXXSTD=-std=c++17

install: 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

notifications:
  email:
    recipients:
    - alekstheod@gmail.com
    on_success: always
    on_failure: always

script:
   cd src && bazel build //... 
before_script:

after_success:
- valgrind --leak-check=full --error-exitcode=1 ./bazel-bin/src/Test/tnnlib_test 1000 > /dev/null
- cd ..
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi
- git checkout -b master
- git pull
- git checkout -b development
- git merge master
- git checkout -b master
- git merge development
- git push -f -q https://alekstheod:$GITHUB_API_KEY@github.com/alekstheod/tnnlib master>/dev/null
branches:
  only:
  - develop
  - master
  email: alekstheod@gmail.com
os:
- linux
dist: xenial
