language: cpp
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    - llvm-toolchain-trusty-5.0
    packages:
    - clang
    - libboost1.68-all-dev
    - cmake
    - valgrind
    - g++-7
    - clang-5.0
  env:
    - CXX=clang++-5.0
    - CXXSTD=-std=c++17

install: 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

notifications:
  email:
    recipients:
    - alekstheod@gmail.com
    on_success: always
    on_failure: always

script:
   cd src && cmake -DCMAKE_DISABLE_FIND_PACKAGE_OpenCL:bool=TRUE CMakeLists.txt && make
before_script:

after_success:
- valgrind --leak-check=full --error-exitcode=1 ./Test/Test 1000 > /dev/null
- cd ..
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi
- git checkout -b master
- git pull
- git checkout -b development
- git merge master
- git checkout -b master
- git merge development
- git push -f -q https://alekstheod:$GITHUB_API_KEY@github.com/alekstheod/tnnlib master>/dev/null
branches:
  only:
  - develop
  - master
  email: alekstheod@gmail.com
os:
- linux
dist: trusty
