cc_test(
    name = "test",
    srcs = glob([
        "NeuronTest.cpp",
    ]),
    deps = [
        "//NeuralNetwork/ActivationFunction",
        "//NeuralNetwork/Neuron",
        "//NeuralNetwork/Serialization",
        "//Utilities/catch2:catch2_main",
        "@catch2",
    ],
)
