jobs:
  build:
    docker:
      - image: l.gcr.io/google/bazel:latest 
    steps:
        - checkout
        - run: bazel test //...
        - run: bazel run --run_under='valgrind --leak-check=full --error-exitcode=1' //src/Test:tnnlib_test
version: 2
