version: 2.1

orbs:
  win: circleci/windows@5

jobs:
  build_in_docker:
    docker:
      - image: l.gcr.io/google/bazel:latest
    steps:
      - checkout
      - run: apt -y install opencl-headers ocl-icd-opencl-dev
      - run: ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so /usr/lib/
      - run: bazel build --config=asan //...
      - run: bazel test --config=asan //... --test_tag_filters="-openCL"
  build_in_windows:
    executor:
      name: win/default
    steps:
      - run:
          name: "Install project dependencies"
          command: echo "Hello from windows"

workflows:
  pr_check:
    jobs:
      - build_in_docker
      - build_in_windows
