cc_library(
    name = "Serialization",
    hdrs = ["Cereal.h"],
    copts = ["-Werror"],
    includes = ["."],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//NeuralNetwork/BackPropagation",
    ],
)
