cc_test(
    name = "builder_tests",
    srcs = glob(["*.cpp"]),
    deps = [
        "//:tnnlib_utils",
        "//NeuralNetwork/ActivationFunction",
        "//NeuralNetwork/NeuralLayer",
        "//NeuralNetwork/Neuron",
        "//NeuralNetwork/Perceptron",
        "@catch2//:catch2_main",
    ],
)
