cc_test(
    name = "test",
    srcs = glob(
        [
            "*.cpp",
        ],
    ),
    deps = [
        "//:tnnlib_utils",
        "//NeuralNetwork/ActivationFunction",
        "//NeuralNetwork/LearningAlgorithm/BackPropagation",
        "//Utilities/catch2:catch2_main",
    ],
)
